# Assignment 4: Forum Discussions {.unnumbered}

### Instructions {.unnumbered}

Students will post a reply to the weekly question posted on the forum page that shows evidence of having read the course material. Students will also be required to ask a question or make a comment on 2 other students’ forum posts to facilitate discussion.

Forum posts need to be completed by the Tuesday following class and the opportunity to post to the forum will be cut off at the start of our next class. Forum posts are about engaging in discussion and late forum posts are not meeting this requirement. I will speak more about this in class. If a post is late, I will not be marking it. Only 5 out of the 6 forums will be marked. You can choose to skip a week, or at the end I will take the 5 highest marks.

**Important:** Discussions are an important part of this online course. Most discussion postings should be no more than 250 words. You are also asked to read your fellow learner’s postings and then respond to at least two other people. All postings should be carefully written and edited before being posted. Opinions should be well supported. Your responses should also be communicated in professional language, respectful of others, and to the point. Forum posts are personal reflections that synthesize the information you have learned with your own experiences. You are not allowed to use AI for forum posts.

### Grading Rubric {.unnumbered}

**Your assignment will be graded according to the following criteria:**

| Criteria | 4-5 marks | 2-3 marks | 0-1 marks |
|-----------|---------|-------|----------|
|**Quality of posting** | Sound evidence that student has done course readings and has a thorough knowledge of discussion topic |Evidence that most of course readings done and student has some knowledge of discussion topic | Minor evidence that course readings were done and student understands discussion topic|
| **Communication skills **| Postings are clear, concise and easy to understand | Postings are usually, but not always clear, concise and easy to understand | Postings are too short/long and/or unclear and hard to understand |
|**Critical thinking and self-reflection** | Exceptionally well- supported, thoughtful, insightful comments made on others’ and own postings | Some evidence of critical thought and self-reflection on others’ and own postings | Minor evidence of critical thought and reflection on others’ and own postings |
|**Participation** | Regularly participates in, and facilitates interaction among members of online community |Interacts now and then with other members of online community | Rarely interacts or responds to other members of online community|
| |  | | **Total /20** |