# Introduction to Psych 339

Welcome to Psych 339! I am excited to begin all of the topics and units that we have planned for the following weeks. There will be a lot of information coming at you, especially in the beginning units, but in later units, we will review and refer back to the information, so my hope is that it won’t feel like too much of an overload.

I would like to take the time here to review a couple of things that may help you navigate your way through this information.

## Assignments

The grading portion of classes can be an anxiety-provoking focus and so I thought I would give you all a couple of tips.

1. All of the questions for the quiz will be taken from the "Questions to Consider" sections in the units. The quiz is open-book and so if you write down the answers as you go through the material, you will have all of the answers at your fingertips when it comes time to take the quiz.
2. You are only required to do three of the six case conceptualizations. I would recommend that you choose the case conceptualizations or topics that you are most interested in, as you will be choosing one of them and writing your final paper on it. We will discuss more about this in class.
3. Oral presentations: You will be placed in groups and assigned a topic—you can also use the information gathered in this assignment to help you write your final paper. You will be required to research and present on one treatment or therapy model known to be effective for the mental health issue you have been assigned.
4. The Discussions should be answered every week. I will not grade comments that are submitted late as you will have missed out on the discussion and participation portion. One free pass is given; if you complete all of the Forum discussion questions then I will use your five best marks for the grade.
5. The final paper is a research paper and should be written as such. We will discuss what is required and how to briefly write a research paper in class.

::: {.note}

*Note:* The Learning Activities in this course are ungraded unless specified. They are designed to help you succeed in your assessments in the course, so you are strongly encouraged to complete them.

:::

## Interconnectedness of the Material

All of the topics that we will be learning about can affect each other, especially trauma, which can be at the root of almost every mental health issue—that is why we are starting with it first. I have not included it in our first unit, but I invite you to watch Gabor Mate’s film *[The Wisdom of Trauma](https://www.kanopy.com/en/product/wisdom-trauma){target="_blank"}.* It is a very meaningful and informative film on the effects of trauma. I also encourage you not to view each unit as a separate unit, but as building upon and being a continuation from each other.

## Research Articles

I have included a smattering of research articles throughout our learnings together. These are the types of articles I would like you to find for your research papers. Research articles must be peer-reviewed and from a reputable source. Research articles, unlike textbooks, often focus on one specific aspect or finding related to the subject. Notice how they provide an overview of the subject in their introductions, and then focus their research specifically on the question they are trying to answer.

## A Note on Emotion-Focused Family Therapy

There are some interventions in the emotion-focused family therapy (EFFT) course resource that we will not be including, as to do so would require target training as well as following the requirement to be a registered therapist with a Master’s degree. However I still invite you to read about clinician chair block work and caregiver chair block work as well as therapeutic apologies, as it is very impactful work.

We will be reviewing the EFFT exercises assigned in each class.

I look forward to our learnings together and hope and pray that this class will be an enriching and helpful experience.
