## Overview {.unnumbered}

Unit 1 explores the complexity of trauma, why it happens, and how to respond to it when it shows up in our work. This unit is designed to provide you with some research, theory, and practical resources so that you will feel confident and competent when you encounter trauma at work or in daily life. Although you will not be expected to become an expert on every topic we will examine, it is imperative that you are able to locate information when confronted with it in order not to become overwhelmed by the large amount and various sources of information available.

### Topics {.unnumbered}

This unit is divided into the following topics:

1. What is Trauma?
2. Why and How Does Trauma Happen?
3. How Do We Work With Trauma?

## Unit Learning Outcomes

When you have completed this unit you will be able to:

- Demonstrate knowledge of some of the major researchers in the field of trauma
- Distinguish between emotional abuse, physical abuse, and sexual abuse
- Identify some of the signs and triggers of trauma
- Begin to conceptualize a trauma case
- Use the validation skill outlined in emotion-focused family therapy (EFFT)
- Develop a preliminary treatment plan and know where to find resources and further specialized training

## Learning Activities

Here is a list of learning activities that will benefit you in completing this unit. You may find it useful for planning your work.

::: {.learning-activity}

1. Read…
2. Watch…
3. Explore…
4. Complete the ungraded quiz.

Working through course activities will help you to meet the learning outcomes and successfully complete your assessments.

:::

### Assessment {.unnumbered}

Please see the Assessment section in Moodle for assignment details.

### Resources {.unnumbered}

Here are the resources you will need to complete this unit.

- Maté, G. (2010). *In the Realm of Hungry Ghosts*. North Atlantic Books.
- Lafrance, A., Henderson, K. A., & Mayman, S. (2020). *Emotion-Focused Family Therapy: A Transdiagnostic Model for Caregiver-Focused Interventions*. American Psychological Association.
- Other online resources will be provided in the unit.

## What is Trauma?

This first unit will lead you to explore some of the research on trauma. Topic 1 will help you not only gain a basic understanding of the varying types of trauma and how to define them, but also identify the main researchers in the field. Learning about the prominent researchers in this field will give you a good foundation and direction to fall back on as you go further in your studies, and as you encounter trauma in your day-to-day activities.

The resources provided for this topic will discuss the areas of the brain trauma affects and how it differs from stress. Dr. Bessel van der Kolk’s famous book *The Body Keeps the Score* (2014) will also be discussed, and we will conclude this section with some definitions and key terms you should know.

## Trauma

Trauma is a very difficult mental health issue to work with. A trauma is a painful, confusing, intergenerational, illogical, interfering, irrational, and shocking experience. The treatment of trauma requires more than a series of four to five sessions; it can be a lengthy and complex process with advances and setbacks.

A trauma can manifest itself in many different ways. Dr. Joseph Spinazzola and Dr. Bessel van der Kolk are prominent researchers in the field of trauma and emphasize that it is not the traumatic incident that remains with people and affects them, but rather unprocessed emotions and going through trauma alone that remains with them. This is also emphasized by Dr. Adele LaFrance, the co-creator of emotionally-focused family therapy (EFFT).

The culture of our society is so geared toward avoiding pain at any cost that when it does emerge we attempt to shut it down and conceal it before it causes too much damage. It is in the avoidance of pain, in the avoidance of the traumatic event, that darkness and maladaptive coping skills emerge, which are often what bring people into therapy.

In the course of working with trauma as therapists, we have the tendency to desire a quick fix or to avoid entering into the dark pit of pain. It can be difficult to navigate this fine line between going too far and experiencing secondary trauma, and avoiding feeling the pain with our clients. As a consequence, we would like to warn you that some of the stories and case studies we will be discussing in this course may be triggering or difficult to listen to. Take note of your ability to engage with the material as the intention is not to create dysregulation within you.

### Activity: What is Trauma?

::: {.learning-activity}

View the following videos and listen to Dr. Bessel van der Kolk, one of the most prominent trauma researchers, then answer the following questions. You may want to watch the first video more than once since a lot of information is packed into a short timeframe.

- [*What is Trauma? The Author of "The Body Keeps the Score" Explains*](http://www.youtube-nocookie.com/embed/BJfmfkDQb14?si=asC9vWgUqFl43TqY){target="_blank"} (2021)

<div class="video-container">

{{< video http://www.youtube-nocookie.com/embed/BJfmfkDQb14?si=asC9vWgUqFl43TqY >}}

</div>

- [*Three Ways Trauma Can Change the Brain*](https://www.youtube.com/watch?v=LKWUmwxi1ZI){target="_blank"} (2014)

<div class="video-container">

{{< video https://www.youtube.com/watch?v=LKWUmwxi1ZI >}}

</div>

**Questions to Consider**

You will be able to check your understanding of the topic by considering these questions.

1. What is the difference between stress and trauma?
2. How does van der Kolk define trauma?
3. Why does it make a difference whether or not PTSD develops if a caregiver or parent is there for us after a traumatic event occurs?
4. What does van der Kolk name as the primitive/survival part of the brain?
5. What emotions do traumatized people have trouble experiencing?
6. What are the three areas that are affected in those who have experienced childhood trauma?

:::

### Activity: Reading | *The Body Keeps the Score*, Prologue

::: {.learning-activity}

Reading the prologue to Dr. van der Kolk’s book will provide you a good introduction to trauma and to his experience and work with it.

- *[The Body Keeps the Score](assets/u1/BKTS_Prologue.pdf){target="_blank"},* Prologue (2014)

**Questions to Consider**

You will be able to check your understanding of the topic by considering these questions.

1. What are some examples of how trauma affects not only the individual, but also those around the individual?
2. What types of physiological change does trauma reproduce?
3. What are the three approaches used in helping heal traumatized individuals?

:::

### Activity: Optional Reading | *The Body Keeps the Score*, Chapter 3

::: {.learning-activity}

If you plan to work with traumatized individuals, Chapter 3 in *The Body Keeps the Score* is an excellent suggested resource for you.

- [The Body Keeps the Score, Chapter 3](assets/u1/TBKTS_Ch.3.pdf){target="_blank"} (2014)

**Highlights from the reading are described in the following paragraphs (van der Kolk, 2014):**

One of the main findings in a study that was conducted by examining the brain with MRI is that trauma is preverbal. While undergoing brain scans, research participants were simultaneously triggered with reminders of their individual traumas. Through this experiment it was discovered that Broca’s area in the brain (where speech resides) was shut down, or dark on the MRI. This is a major finding as it tells us that the connection between speech and what is happening is disconnected. Similarly, it was shown that when something happens to remind traumatized people of their trauma, their right brain responds as if the event was happening in the present, while their left side of the brain is shut down, which can block the realization that the event is not happening in real time. This is all experienced in the bodily-felt sense. This therefore means that the experience of trauma itself can get in the way of talking about the trauma. This piece of information is crucial to know as therapists, because the process of change in the therapy room often involves talking.

van der Kolk also describes trauma succinctly in this chapter. He describes trauma as something that happens to you that makes you so upset that it overwhelms you and there is nothing you can do to help yourself function in the face of the particular event. Trauma is how you respond to it.

:::

### Activity: A Note on Childhood Trauma and Adverse Childhood Experiences

::: {.learning-activity}

There are two sections to this activity. In the first, Dr. van der Kolk explains how trauma manifests in children, and in the second, pediatrician Nadine Burke Harris shares during a TED Talk the importance of acknowledging childhood trauma and how it impacts our physical well-being.

- [*Bessel van der Kolk on the Treatment of Trauma: How Childhood Trauma is Different from PTSD*](https://www.youtube-nocookie.com/embed/UxPAt-Esv8Q){target="_blank"}(2013)

<div class="video-container">

{{< video https://www.youtube-nocookie.com/embed/UxPAt-Esv8Q >}}

</div>

Pediatrician Nadine Burke Harris explains that the repeated stress of abuse, neglect, and parents struggling with mental health or substance abuse issues has real, tangible effects on the development of the brain. Watch the following video:

- *[How Childhood Trauma Affects Health Across a Lifetime](https://www.youtube.com/watch?v=95ovIJ3dsNk){target="_blank"}* (2015)

<div class="video-container">

{{< video https://www.youtube-nocookie.com/embed/95ovIJ3dsNk >}}

</div>

**Questions to Consider**

You will be able to check your understanding of the topic by considering these questions.

1. How does PTSD manifest in children?
2. What areas of the brain does trauma affect?
3. Why are children more sensitive to brain change from trauma?

To gain a better understanding of your own past experiences, you can take the following short adverse childhood experience (ACE) quiz found on the website below. It is important to note that participation in this activity is not mandatory, nor will you be asked to share your experiences. Please proceed with caution and awareness as the questions and discoveries may be triggering.

- *[Take Your ACE Test](https://stopabusecampaign.org/take-your-ace-test/){target="_blank"}* (n.d.)

:::

### Activity: Terminology

::: {.learning-activity}

This activity will introduce you to some of the concepts and terminology used in this field by looking up the following terms. The website given here is recommended for searching the terms listed in the tool below. By doing the search yourself you are more likely to remember the definitions. Try to write out or type out the definitions instead of just copying and pasting them. This section aims to define these terms at the end of the section rather than at the beginning so you will recognize some of them and have a context from the resources you have read.

- [*Complex Trauma Resources*](https://www.complextrauma.org/glossary){target="_blank"} (n.d.)

Use the tool below to assist you in this activity. Please note that if you close or refresh the page your work will be lost, so you may wish to download the file with your answers before closing the browser.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=449" width="100%" height="100%" frameborder="0" allowfullscreen="allowfullscreen" title=""></iframe><script src="https://h5p.org/sites/all/modules/h5p/library/js/h5p-resizer.js" charset="UTF-8"></script>

:::

## Why and How Does Trauma Happen?

To develop a preliminary understanding of why trauma occurs, you have learned defining terms in the previous topic. This topic will focus on why and how PTSD develops and persists—we often tend to focus on the "why" of abuse; however PTSD is not something to discuss in the beginning. The learning activities included in this topic will allow you to explore the reasons why the brain and body can perceive an event as if it were happening right now, even when an event or series of events occurred in the past. Furthermore, the resources will discuss what happens to our brains when trauma occurs and persists over time. Despite some repetition in the resources, the expectation is that you will retain more of the information by digesting it through various sources and formats.

### Activity: Reading | *The Body Keeps the Score*, Chapter 4

::: {.learning-activity}

Despite being potentially overwhelming, this chapter is extremely informative regarding what happens to the brain when trauma occurs. Please use the following questions to guide your reading, as they will assist you in focusing on the most important information.

- Watch [*What is trauma? The author of "The Body Keeps the Score" explains | Bessel van der Kolk | Big Think*](https://www.youtube.com/watch?v=BJfmfkDQb14){target="_blank"}.

<div class="video-container">

{{< video https://www.youtube.com/watch?v=BJfmfkDQb14 >}}

</div>

- Read [*The Body Keeps the Score*](../U1%20Files/TBKS_Ch_4.pdf){target="_blank"}, Chapter 4 (2014)

> "When you can’t be fully here, you go to the places where you did feel alive—even if those places are filled with horror and misery (van der Kolk, p. 73)."

**Questions to Consider**

You will be able to check your understanding of the topic by considering the following questions.

1. What happens to the brain when the normal response is blocked?
2. What are the five things our brains need to do in order to ensure our survival?
3. What does "neurons that fire together, wire together" mean?
4. What are frontal lobes responsible for?
5. What are mirror neurons?
6. What is the difference between top-down regulation and bottom-up regulation?
7. Why can flashbacks and reliving trauma almost be worse than experiencing the trauma?
8. What parts of the brain need to be "online" in order to visit past traumatic memories?

:::

### Activity: Reading | *In the Realm of Hungry Ghosts*, Chapters 17 and 18

::: {.learning-activity}

Gabor Maté’s book, *In the Realm of Hungry Ghosts* (2010), focuses on addiction. You may want to spend some time reading Chapters 17 and 18 to better understand how addiction and trauma are intertwined.

Maté is famous for saying, "don’t ask why the addiction, but why the pain." He would state that every person who has an addiction has experienced trauma (Maté, 2010). Thus, we will read a few chapters from the book that describe how the brain develops and works. Observe how Maté describes both physical trauma and emotional trauma. The need for strong attachment figures from a young age has been discussed and will continue to be discussed—this section explains the effects on the brain and brain development. Our next unit on addiction will benefit from investigating the effects on the brain.

- *In the Realm of Hungry Ghosts: Close Encounters With Addiction* (2010)

**Questions to Consider**

You will be able to check your understanding of the topic by considering the following questions.

1. How much smaller do mistreated children’s brains tend to be?
2. What part of the brain tends to be smaller in trauma survivors? What is this part of the brain responsible for?
3. What is the stress hormone called?
4. What does early stress establish in a child?
5. How does early abuse and neglect affect interpersonal relationships?
6. What are three universal factors that lead to stress?

:::

### Activity: Optional Website Reading | *The Effects of Complex Trauma on Brain Development*

::: {.learning-activity}

Complextrauma.org is an excellent website to familiarize yourself with for research and information about trauma, as well as for resources and opportunities. In addition to using this site to define some terms, I invite you to read the following explanation of the impact trauma has on the brain. Hopefully, some of this information will sound familiar to you.

- [*The Effects of Complex Trauma on Brain Development*](https://www.complextrauma.org/complex-trauma/the-effects-of-complex-trauma-on-brain-development/){target="_blank"} (n.d.)

:::

### Activity: Optional Reading | *Treating Adult Survivors of Childhood Emotional Abuse and Neglect*, pp. 3–12

::: {.learning-activity}

Literature in this section discusses emotional abuse or neglect and psychological trauma. Emotional and psychological trauma is a relatively new and complex area of trauma study, and it is crucial that we learn how this affects the systems in which we live, work, and commune. As you read this section, keep the authors’ working definition of complex trauma in the back of your mind—they identify complex trauma as defined by Courtois (2004) and Courtois & Ford, (2010):

"Courtois (2004) articulated … complex trauma as a *recurrent* and *escalating* form of trauma, occurring primarily within familial or intimate relationships ... requiring survival to take precedence over normal psychobiological development" (Courtois & Ford, 2010, as cited in Hopper et al., 2021, p. 9).

Additionally, they note that the Complex Trauma Workgroup has a similarly developmentally anchored definition of complex trauma as "a *dualistic*, pernicious, and *progressive relationship* *between exposure and adaptation*" (as cited in Hopper et al., 2021, p. 9).

- Read pages 3 to 12 in [*Treating Adult Survivors of Childhood Emotional Abuse and Neglect: Component-Based Psychotherapy*](../U1%20Files/Survivors_of_Emotional_Abuse_and_Neglect.pdf){target="_blank"} (2021)

**Questions to Consider**

You will be able to check your understanding of the topic by considering the following questions.

1. Can you describe the difference between emotional abuse versus emotional neglect?
2. Why does psychological maltreatment in the home still largely remain in a gray area? What factors make it hard to identify or intervene?
3. What is psychological abuse the strongest predictor of?
4. How does Courtois (2004) define complex trauma?
5. What is the difference between Type I trauma and Type II trauma?
6. What do the acronyms PTSD, CPTSD, and DTD stand for?

:::

## How Do We Work With Trauma?

During this topic you will become familiar with and comfortable with one main therapeutic approach. The purpose is to give you some practical skills and applications, rather than just a variety of theories that you would need to study further in order to implement. Consequently, this topic may feel more overwhelming, due to the repetition of the same information with a slightly different application. In this section, we will begin by learning about emotion-focused family therapy (EFFT) and then we will apply it specifically to the treatment of trauma.

There are many therapy modalities that are specifically designed for trauma; EFFT is an all-encompassing modality and not trauma-specific. In the final activity you will be provided with a list of trauma-informed therapies that you can pursue at your own leisure. If you come into contact with someone who has complex trauma or PTSD at this stage of your studies, it is best to refer them to someone who is qualified and trained to work with PTSD.

> In our view, successful complex trauma intervention in real-life practice—particularly when conducted with adult survivors of the kind of pervasive and profound deprivation and debasement that comes from living through chronic and severe emotional abuse and neglect in childhood—can almost never be accomplished through adoption of a singular clinical target, follow a consistently linear process, or result from adherence to one specific clinical technique. In contrast, it is tangled, precarious work, work that is predictable in its unpredictability, that inevitably requires the therapists’ extensive use of themselves in the treatment process and that simultaneously demands attention to the body and all that usually goes unspoken in trauma and psychotherapy. (Hopper et al., 2021, pp. 14–15)

### Activity: Optional Reading | *Treating Adult Survivors of Childhood Emotional Abuse and Neglect*

::: {.learning-activity}

Read the following article for a description of a new framework for treating childhood emotional abuse and neglect. This article describes component-based psychotherapy. This is not an essential therapy for you to know as we will be focusing on learning about emotionally-focused family therapy in our time together, but if you are interested in working with trauma or have done so previously, I would recommend reading this article.

- [Treating Adult Survivors of Childhood Emotional Abuse and Neglect](assets/u1/Survivors_of_Emotional_Abuse_and_Neglect.pdf){target="_blank"} (2021)

**Questions to Consider**

You will be able to check your understanding of the topic by considering the following questions.

1. What are the three predominant paradigms that have emerged regarding traumatic stress inquiry and research?
2. What does CBP stand for? What are some preliminary characteristics of the model?

:::

### Activity: Optional Reading | *Complex Trauma and the Christian Context*

::: {.learning-activity}

An adult with complex trauma history frequently experiences disrupted systems of meaning, which can lead to adversely affected belief systems. The experiences of shame, betrayal, meaning-making, and mourning experienced by adult survivors of childhood trauma often complicate their spiritual or religious beliefs. The goal of this activity is to provide you with a better understanding of how a complex trauma treatment is applied within a Christian context.

- [*Beyond Survival: Application of a Complex Trauma Treatment Model in the Christian Context*](assets/u1/Beyond_Survival.pdf){target="_blank"} (2015)

**Questions to Consider**

You will be able to check your understanding of the topic by considering the following questions.

1. Why is it vital for a therapist to "know thyself" as this article highlights? How can a therapist’s own religion or faith get in the way of trauma therapy?
2. What is the importance of relational rupture and repair? What are the reasons for allowing therapeutic ruptures to occur?
3. Why is the skill of validation important?
4. Why would it be beneficial to explore a client’s view of God and God’s view of themselves?
5. What is MBCT and how can it be beneficial?
6. Why is it easy in a Christian environment to confuse dysregulated behaviour with willful sin?

:::

### Activity: Reading | Emotion-Focused Family Therapy, pp. 3–48

::: {.learning-activity}

Read pages 3–48 in your course resource below. The purpose of this unit is to process this new model and make our own deductions regarding how this model may be applied to the treatment of trauma.

- [*Emotion-Focused Family Therapy: A Transdiagnostic Model for Caregiver-Focused Interventions*](assets/u1/Survivors_of_Emotional_Abuse_and_Neglect.pdf){target="_blank"} (2020)

**Questions to Consider**

You will be able to check your understanding of the topic by considering the following questions.

1. What is EFFT?
2. What are the core principles of EFFT?
3. What are advanced caregiving skills?
4. What are the six pillars of EFFT?
5. What are some of the themes that research of EFFT has shown?
6. What areas does the bridge responsible for emotion regulation connect? (which parts of the brain?)
7. What are some of the benefits of emotion coaching?
8. What happens over time when emotion coaching is present?
9. What is a super feeler?
10. What are the five steps of emotion coaching?
11. What is the two-step model of emotion coaching?
12. What is the "good house–bad house" metaphor?

:::

> When you come from a place where you were not allowed to know what you know or feel what you feel, it can be extraordinarily difficult to find a language for yourself and your inner experience. The presence of a compassionate, safe, and reflective therapist is essential to help you discover who you are and what is going on inside. This is never an easy process, and the main task of the therapist is to create physiological stability and the necessary safety to activate the "watchtower of the mind" (van der Kolk, 2014), where we can compassionately observe ourselves and examine our warring fears, longings and impulses. (Hopper et al., 2021, xiii)

The chapters of our EFFT resource contain a great deal of information to process and absorb. As a result, we will not spend much time applying specific interventions to trauma scenarios in this section.

Please do your own application in the case study below, as well as the corresponding Forum Discussion question. The case study provides an opportunity for you to practice the skill of validation. Don’t worry if this seems confusing. This scenario will be discussed in class. Also consider how this model could be applied to trauma work theoretically. We will work on specific interventions in future units.

### Activity: Optional Exploration | Trauma-Informed Therapies

::: {.learning-activity}

Look up the following modalities to see what types of treatment options are available and notice which modalities resonate with you and why. These modalities do not require in-depth knowledge. Again, the aim is to provide you with a foundation so that when you encounter trauma in your work environment, you will already know which modality resonates with you and in which you would benefit from further training.

- [EMDR Therapy: Demonstration & Step-by-Step Walkthrough](https://www.youtube.com/watch?v=M2ra8p4MSOk){target="_blank"} (2021)
- [*Narrative Exposure Therapy (NET)*](https://www.apa.org/ptsd-guideline/treatments/narrative-exposure-therapy){target="_blank"} (2025)
- [*Origin of Somatic Experiencing*](http://www.youtube.com/watch?v=L0PsQFoz48g&t=33s){target="_blank"} (2012)
- [Internal Family Systems & CBP & AEDP & STAIR/MPE](https://www.complextrauma.org/treatment/complex-trauma-treatments-for-adults/){target="_blank"} (2019)
- [ARC Therapy](https://arcframework.org/what-is-arc/){target="_blank"} (2020)

:::

### Activity: Case Study

::: {.learning-activity}

Take note of the following questions as you read the case study below. An overview of David, the client, is provided in this case study, followed by snapshots of his therapy.

- [*Open Case Study*](assets/u1/CaseStudy.pdf){target="_blank"}

**Case Study Notes**

Take notes using the tool below. You may wish to download your notes (please consider that if you close your browser, your answers will be lost).

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=456" width="100%" height="100%" frameborder="0" allowfullscreen="allowfullscreen" title=""></iframe><script src="https://h5p.org/sites/all/modules/h5p/library/js/h5p-resizer.js" charset="UTF-8"></script>

:::

# References and Resources

## What is Trauma?

**Videos**

- Big Think. (2021). *What is trauma?* The author of "The Body Keeps the Score" explains [Video]. [https://www.youtube.com/watch?v=BJfmfkDQb14](https://www.youtube.com/watch?v=BJfmfkDQb14){target="_blank"}
- NICABM. (2014). *Three ways trauma can change the brain* [Video]. YouTube. [https://www.youtube-nocookie.com/embed/LKWUmwxi1ZI](https://www.youtube.com/watch?v=LKWUmwxi1ZI){target="_blank"}
- TED. (2015, February 18). *How childhood trauma affects health across a lifetime* [Video]. YouTube. [https://www.youtube-nocookie.com/embed/95ovIJ3dsNk](https://www.youtube.com/watch?v=95ovIJ3dsNk){target="_blank"}

**Readings**

- van der Kolk, B. (2015). *The body keeps the score: Brain, mind, and body in the healing of trauma*. Penguin.

**Websites**

- Complex Trauma. (n.d.). *Complex trauma resources: Glossary*. [https://www.complextrauma.org/glossary/](https://www.complextrauma.org/glossary/){target="_blank"}

## Why and How Does Trauma Happen?

**Videos**

- There are no recommended videos for Topic 2.

**Readings**

- Courtois, C. (2004). Complex trauma, complex reactions: Assessment and treatment: *Psychotherapy: Theory, Research, Practice, Training*, *42*(4), 412–425.
- Courtois, C., & Ford, J. D. (Eds.). (2009). *Treating complex traumatic stress disorder: Scientific foundations and therapeutic models*. Guilford Press.
- [Hopper, E. K., Grossman, F. K., Spinazzola, J., & Zucker, M. (2021). *Treating adult survivors of childhood emotional abuse and neglect: Component-based psychotherapy*. The Guilford Press.](https://d.docs.live.net/47342b2749fd82eb/Desktop/_Trinity%20Western_Editing/Psych%20339/1.%20Original%20Files%20From%20Production/assets/u1/Beyond_Survival.pdf){target="_blank"}
- Maté, G. (2010). *In the realm of hungry ghosts*. North Atlantic Books.
- van der Kolk, B. (2015). *The body keeps the score: Brain, mind, and body in the healing of trauma*. Penguin.

**Websites**

- Complex Trauma. (n.d.). The effects of complex trauma on brain development. [https://www.complextrauma.org/complex-trauma/the-effects-of-complex-trauma-on-brain-development/](https://www.complextrauma.org/complex-trauma/the-effects-of-complex-trauma-on-brain-development/){target="_blank"}

## How Do We Work with Trauma?

**Videos**

- [EMDR Therapy: Demonstration & Step-by-Step Walkthrough](https://www.youtube.com/watch?v=M2ra8p4MSOk){target="_blank"}
- Somatic Experiencing International. (2012). *Origin of somatic experiencing* [Video]. YouTube. [https://www.youtube.com/watch?v=L0PsQFoz48g](https://www.youtube.com/watch?v=L0PsQFoz48g){target="_blank"}

**Readings**

- Hopper, E. K., Grossman, F. K., Spinazzola, J., & Zucker, M. (2021). *Treating adult survivors of childhood emotional abuse and neglect: Component-based psychotherapy*. Guilford Press.
- Lafrance, A., Henderson, K. A., & Mayman, S. (2020). *Emotion-focused family therapy: A transdiagnostic model for caregiver-focused interventions*. American Psychological Association.
- Pressley, J., & Spinazzola, J. (2015). Beyond survival: Application of a complex trauma treatment model in the Christian context. *Journal of Psychology and Theology*, *43*(1), 8–22. [https://psycnet.apa.org/doi/10.1177/009164711504300102](https://psycnet.apa.org/doi/10.1177/009164711504300102){target="_blank"}

**Websites**

- American Psychiatric Association. (n.d.). *PTSD guideline*. [https://www.apa.org/ptsd-guideline/treatments/narrative-exposure-therapy](https://www.apa.org/ptsd-guideline/treatments/narrative-exposure-therapy){target="_blank"}
- Complex Trauma Resources. (n.d.) *Treatments for adults - Accelerated experiential dynamic psychotherapy (AEDP)*. [https://www.complextrauma.org/treatment/complex-trauma-treatments-for-adults/](https://www.complextrauma.org/treatment/complex-trauma-treatments-for-adults/){target="_blank"}
- Stop Abuse Campaign. (n.d.). *Take your ACE test*. [https://stopabusecampaign.org/take-your-ace-test/](https://stopabusecampaign.org/take-your-ace-test/){target="_blank"}
- ARC Framework. (n.d.) *What is ARC*. [https://arcframework.org/what-is-arc/](https://arcframework.org/what-is-arc/){target="_blank"}
- Somatic Experiencing International. (2012). *Origin of somatic experiencing* [Video]. YouTube. [https://www.youtube.com/watch?v=L0PsQFoz48g](https://www.youtube.com/watch?v=L0PsQFoz48g){target="_blank"}

## Summary {.unnumbered}

In this first unit, you have been introduced to some of the researchers in the field of trauma, and have developed your ability to conceptualize a case that involves trauma. During this unit we were only able to touch on the surface of the research that has been conducted in this area. I hope that you will leave this unit with an understanding of where to turn for assistance, what resources you can access, and how to interact with trauma in therapy.

::: {.check}

Before you move on to the next unit you may want to check that you are able to:

- Demonstrate knowledge of some of the major trauma researchers
- Distinguish between emotional abuse, physical abuse, and sexual abuse
- Identify some of the signs and triggers of trauma
- Begin to conceptualize a trauma case
- Use the validation skill outlined in EFFT
- Develop a preliminary treatment plan and know where to find resources and further specialized training

:::
