## Overview {.unnumbered}

Your journey through this course has reached the halfway point. We will discuss three major mental health issues in this unit: depression, suicidality, and eating disorders. As part of this unit we will examine what a mental health issue is, why it occurs, and how it can be dealt with. These topics, like all of our topics so far, can be difficult and triggering. We encourage you to take breaks, to skim or to skip sections if you find them triggering.

### Topics {.unnumbered}

This unit is divided into the following topics:

1. What are Depression, Suicidality, and Eating Disorders?
2. What Causes Mental Health Issues?
3. How Do We Work With Mental Health Issues?

### Unit Learning Outcomes {.unnumbered}

When you have completed this unit you will be able to:

- Demonstrate knowledge of some of the major researchers in the field of mental health
- Engage in conversations about suicidality, eating disorders, and self-harm
- Start conceptualizing mental health crisis cases
- Practice the skill of validation as outlined in EFFT
- Develop a preliminary treatment plan and know where to find resources and further specialized training

### Learning Activities {.unnumbered}

Here is a list of learning activities that will benefit you in completing this unit. You may find it useful for planning your work.

::: {.learning-activity}

1. Read…
2. Watch…
3. Explore…
4. Complete the ungraded quiz.

::: {.note icon="true"}

Working through course activities will help you to meet the learning outcomes and successfully complete your assessments.

:::

:::

## Assessment {.unnumbered}

Please see the Assessment section in Moodle for assignment details.

### Resources {.unnumbered}

Here are the resources you will need to complete this unit.

- Lafrance, A., Henderson, K. A., & Mayman, S. (2020). *Emotion-Focused Family Therapy: A Transdiagnostic Model for Caregiver-Focused Interventions*. American Psychological Association.
- Other online resources will be provided in the unit.

# What are Depression, Suicidality, and Eating Disorders?

Suicidality, eating disorders, and depression are some of the "main" mental health issues that one might encounter in the therapy room. These issues will only be touched upon in this unit. In our EFFT text we have been learning that mental health issues are caused by unprocessed emotions. Rather than experiencing things that cause mental health issues, it is experiencing them alone without the ability to process what is happening that causes the issue. According to EFFT, mental health issues would not occur if we were able to process emotions correctly. Both trauma and addiction can be comorbid.

It may seem that the first two topics are disjointed from previous topics, but the purpose is to pique your interest and introduce you to the researchers and clinicians in this field. Throughout this unit I encourage you to draw upon and incorporate what you have learned in the previous units, particularly about the brain and how it interacts with these issues.

## Depression

The medical term depression (major depressive disorder) refers to a serious, common psychological illness that negatively affects a person’s feelings, thoughts, and actions. An individual suffering from depression may experience sadness and/or a loss of interest in activities they previously enjoyed. Depression may also make it difficult for an individual to perform their duties at work or at home. There may be a variety of emotional and physical problems associated with it.

There is a wide range of symptoms associated with depression, ranging from mild to severe. These include feeling sad or depressed, losing interest in activities that used to be enjoyable, losing weight or gaining weight because of changes in appetite, oversleeping, difficulty sleeping, fatigue, feelings of worthlessness or guilt, difficulty concentrating, thinking, or making decisions, and thoughts of suicide or death.

### Activity: Video | Neuroscience of Depression

::: {.learning-activity}

I invite you to watch the following YouTube clip to introduce yourself to the various hypotheses that link brain activity to the development and maintenance of depression.

- [*10-Minute Neuroscience: Depression*](https://www.youtube.com/watch?v=1euK8OSIR9E){target="_blank"} (2023)

**Questions to Consider**

- What are some of the hypotheses that this video covers?
- What has been the traditional or original hypothesis? Why?
- What is neuroplasticity and neurogenesis?
- What area of the brain does neuroplasticity and neurogenesis take place in?

**Optional Video | How Depression Affects the Brain**

- [*How Depression Affects the Brain – Yale Medicine Explains*](https://www.youtube.com/watch?v=BZOLxSQwER8){target="_blank"} (2021)

:::

### Activity: Read | *I Don’t Want to Talk About It*

::: {.learning-activity}

In his work as a psychotherapist, Terry Real has made a significant contribution to the discussion of male depression and advocacy for it. The publication of his book *I Don’t Want to Talk About It* (1998) created a significant wave in the field of psychology, and he has been presenting on the subject ever since. Real incorporates his own narrative and his own journey through depression into the book. The teaser below is only a brief excerpt, and you are encouraged to read the whole book.

- [*Men’s Hidden Depression*, Chapter 1](../U4%20Files/Real_Ch_1.pdf){target="_blank"} (1998)

**Questions to Consider**

After reading the chapter consider the following questions:

1. How does this description of Real’s father relate to the intersection of both trauma and depression?
2. Why do we tend not to recognize depression in men?
3. What is the percentage of people who never get help for depression?
4. What, according to Real, produces depression?
5. What are some of the signs of depression in men?
6. What do people tend to view depression as?
7. What compounds a depressed man’s condition?
8. Why do men die earlier than women?
9. What is the stigma around depression?
10. What is covert depression?

Please view the following video, not for information regarding psychotherapy or suicide psychology, but rather to understand what Terry Real is describing as male hidden depression in this video.

- [*What I Learned From My Husband’s Suicide*](https://www.youtube.com/watch?v=Jb_1IklnhaU){target="_blank"} (2020)

:::

### Activity: Familiarize Yourself With the PHQ-9

::: {.learning-activity}

Take a moment to read a patient health questionnaire that is commonly used to assess depression in patients. This is one of many scales available.

- [*Patient Health Questionnaire—PHQ-9*](https://www2.gov.bc.ca/assets/gov/health/practitioner-pro/bc-guidelines/depression_patient_health_questionnaire.pdf){target="_blank"} (1999)

:::

## Suicidality

Suicidality includes suicide attempts as well as suicidal ideation. A suicidal ideation is the presence of suicidal thoughts. A person may experience suicidal ideation in a variety of ways, from fleeting and unwelcome thoughts, to a preoccupation with death that requires extensive planning.

In this section you will read older sources which provide a very good explanation of what suicide is. It is important to note, however, that we no longer refer to someone as committing suicide, but rather as someone dying by suicide. Making this distinction is important, as it emphasizes the importance of depression and suicide, and how in those extremely dark moments, it would not be a choice to commit suicide.

### Activity: Watch & Read | Shneidman

::: {.learning-activity}

Edwin Shneidman is known as the "father of suicide" and has used the term "psychache" to describe the psychological pain that underlies suicidal acts. Take note in this article of both his name and the reference to his coined term "psychache," as it is one of our goals throughout this course to refer to some of the original researchers.

Watch the following video of Dr. Shneidman talking about some of his work.

- [*My Suicide Shneidman Sequence QT*](https://www.youtube.com/watch?v=0KAE5IGOTxw){target="_blank"} (2014)

**Questions for Reflection**

1. How did you respond to the way Shneidman talks about suicidology?
2. Is there anything that you would agree or disagree with and why?

Read Shneidman’s [*Contributions to the Understanding of Suicidal Thinking*](../U4%20Files/Cognition_and_Suicide.pdf){target="_blank"} (2006)

**Questions to Consider**

1. What is psychache?
2. What did Shneidman analyze as his preliminary research?
3. What are the 10 commonalities of suicide?
4. What is the cubic model of suicide?
5. What is the most dangerous period for a suicide attempt?
6. What measure did Shneidman develop?
7. What was a central aspect to Shneidman’s clinical approach?
8. What is anodyne therapy? How does it relate to EFFT?

:::

### Activity: Read | Suicide Clusters

::: {.learning-activity}

Read the following research article about suicide clusters.

- [*Suicide Clusters: A Review of Risk Factors and Mechanisms*](https://doi-org.twu.idm.oclc.org/10.1111/j.1943-278X.2012.00130.x){target="_blank"} (2013)

Watch the following video about suicide clusters (note that the video is 6:42 minutes long).

- [*‘Suicide Cluster’ in Palo Alto: Students Share Stories of Anxiety, Depression*](https://www.youtube.com/watch?v=F6S3jcJ-Imw){target="_blank"} (2016)

**Questions to Consider**

Consider the following questions to help guide your learning.

1. What is the definition of a suicide cluster?
2. What are the two types of clusters?
3. What population is most at risk for suicide clusters?
4. What gender are suicide clusters more common among?
5. Where is the copycat effect more prevalent?
6. What does "contagion" mean?
7. What is the Werther effect?
8. What does the process of imitation rely on?
9. What is priming?
10. List some of the proposed theories of suicide clusters.

:::

## Eating Disorders

An eating disorder is a behavioural condition characterized by persistent and severe disturbances of eating behaviours, as well as distressing thoughts and emotions. Physical, psychological, and social functioning can all be affected by these conditions. In addition to anorexia nervosa, bulimia nervosa, binge eating disorder, avoidant restriction of food intake disorder, and pica and rumination disorders, there are several other eating disorders.

### Activity: Watch | What is an Eating Disorder?

::: {.learning-activity}

Cynthia Bulik, a leading researcher in the field of eating disorders, gives an overview of what eating disorders are and how common they are.

- [*Cynthia Bulik on Eating Disorders*](https://www.youtube.com/watch?v=Fxe6WLNSxcw){target="_blank"} (2010)

**Questions to Consider**

After watching the video consider the following questions to help you track your learning.

1. What are the three different types of eating disorders discussed and what are their descriptions?
2. How prevalent are eating disorders?
3. What contributes to an eating disorder?
4. In which eating disorder is the sex ratio more equal?
5. What new research is coming?

:::

### Activity: Optional Read | Emotional Eating

::: {.learning-activity}

Janet Treasure is a well-known therapist and professor in the field of eating disorders in England. She has published a number of papers, and also focuses on the role of the family in the healing process. Her animal models appear in our manual on EFFT.

Read the following article by Treasure and her colleagues (2022):

- [*Novel Approaches to Tackling Emotional Loss of Control of Eating Across the Weight Spectrum*](https://www.cambridge.org/core/journals/proceedings-of-the-nutrition-society/article/novel-approaches-to-tackling-emotional-loss-of-control-of-eating-across-the-weight-spectrum/320DBB5D71D83A6C8597BEFAE7BAAEA9){target="_blank"} (2022)

**Questions to Consider**

After reading, consider the following questions and use them to help you keep track of your learning.

1. What are the three types of eating disorders?
2. Why don’t people with binge eating disorder generally seek help?
3. What risk factors are associated with binge eating disorder?
4. What system in the brain is overeating associated with?
5. What might drive overeating after it becomes a habit? Changing from "outcome driven" to …?
6. What are the key neurotransmitters involved in body weight, appetite, and food intake?

:::

# What Causes Mental Health Issues?

The aim of this discussion is to explore some of the potential causes of mental health issues. It’s important to note that identifying a single cause of mental illness is often difficult, as multiple factors can contribute to its development. As we have previously discussed, these factors may include early adverse life experiences such as trauma, as well as a history of abuse, whether directly experienced or witnessed. Refer back to the diagram we looked at earlier, which outlines various contributors to the development of mental health issues. Extensive research also shows that mental health problems can be linked to chronic medical conditions such as cancer or diabetes. Additionally, biological factors, chemical imbalances in the brain, and changes in brain structure due to alcohol or drug use can play significant roles. Our brains, bodies, and emotions are deeply interconnected, making it challenging to pinpoint direct causes and effects.

In this section we will discuss some of the research behind why mental health issues occur. As we continue our study of the brain, draw upon the knowledge you have gained from the previous units. The topic of depression will be discussed first, followed by suicidality, and then eating disorders.

## Depression

While depressive disorders are often labelled as chemical imbalances, this oversimplifies their complexity. Research shows that depression isn’t simply caused by a lack or excess of certain brain chemicals. Factors such as faulty mood regulation, genetic vulnerability, and stressful life events all contribute, often interacting with one another. Individuals with similar symptoms of depression may have entirely different underlying causes, and respond to different treatment approaches.

### Activity: Read | *I Don’t Want to Talk About It*, Chapter 4

::: {.learning-activity}

Terry Real’s book provides insight into how and why depression develops. This chapter will focus on the relationship between trauma and depression, which we discussed extensively in our first unit.

As you will see in the following chapter, Real is a very systemic therapist. Notice the emphasis on process rather than content—**how** the client is showing up rather than what the client wishes to discuss or share. Observe how Real’s approach relates to our learning of EFFT.

- [*I Don’t Want to Talk About It*, Chapter 4](../U4%20Files/Real_Ch_4.pdf){target="_blank"} (1998)

**Questions to Consider**

After reading this chapter, consider the following questions and use them as a tool to help you process the information from your reading.

1. Why is crisis a potential ally in therapy?
2. What is a body memory?
3. What needs to stop in order for underlying depression to rise to the surface?
4. What did John Bowlby study and how does it relate to the manifestation of depression?
5. What does childhood injury in boys create?
6. What is major depression versus dysthymia?

:::

### Activity: Optional Read | *The Bible*, Psalm 88

::: {.learning-activity}

- Take a look at [Psalm 88](https://www.biblegateway.com/passage/?search=Psalm%2088&version=NIV){target="_blank"}, one of the darkest psalms in the Bible.

**Reflect**

- In what state is the author in despair and what questions does he ask?
- Is there anything in this that stirs your emotions?

:::

## Suicide

Suicide ideation is a very prevalent issue in our society. For those who have never experienced suicide ideation or been close to that moment of contemplation, it can be difficult to imagine the reasoning behind how this can occur. In this next section we will explore why suicide ideation might occur and why such ideation can lead to dying by suicide. As with our previous units, we will spend time looking at the brain and what brain activity occurs when suicide ideation is present.

### Activity: Video | Suicide and the Brain

::: {.learning-activity}

Dr. Daniel Amen is a prominent researcher who studies the brain in relation to mental health problems; we have previously discussed some of his work.

He is not a very empathetic speaker, and some do not agree with some of his approaches (for example guilting clients). Nevertheless, he is a solid researcher and it is important to understand his perspective and how he looks at the brain.

- [*The Science Behind Suicidal Thoughts*](https://www.youtube.com/watch?v=GJkTElq8UFM){target="_blank"} (2019)

**Questions to Consider**

After watching the video consider the following questions and use them as a tool to help you process the information.

1. What is the percentage of people who have entertained the thought of suicide?
2. How many have attempted suicide?
3. In those who died by suicide, what area of the brain had lower functioning?
4. What are some conditions that can be associated with dying by suicide?

:::

### Activity: Read | Risk Factors for Depression and Suicide Ideation

::: {.learning-activity}

In this activity you will read two articles and reflect on their respective questions. The second article is an optional read. In the first article you will learn about the risk factors associated with adolescents with complex depression.

Van Velzen, L. S., Toenders, Y. J., Kottaram, A., Youzchalveen, B., Pilkington, V., Cotton, S. M., Brooker, A., McKechnie, B., Rice, S., & Schmaal, L. (2022). Risk factors for suicide attempt during outpatient care in adolescents with severe and complex depression. *Crisis: The Journal of Crisis Intervention and Suicide Prevention*.

- [*Risk Factors for Suicide Attempt During Outpatient Care in Adolescents With Severe and Complex Depression*](https://econtent.hogrefe.com/doi/10.1027/0227-5910/a000860){target="_blank"} (2022)

**Questions to Consider**

After reading, consider the following questions and use them as a tool to help you process the information.

1. Why is suicide risk assessment a crucial part of suicide prevention?
2. What are some of the risk factors that have been identified by previous studies?
3. What are some risk factors identified by this study?
4. How might parental divorce or separation increase suicide risk in adolescents?
5. What were the authors’ conclusions?

Here is an article that addresses all three mental health issues that we are discussing. As we have stated previously, mental health issues have the potential to affect one another and coexist with one another.

- [*The Role of Body Image and Disordered Eating as Risk Factors for Depression and Suicidal Ideation in Adolescents*](https://d.docs.live.net/47342b2749fd82eb/Desktop/_Trinity%20Western_Editing/Psych%20339/1.%20Original%20Files%20From%20Production/assets/u4/The_Role_of_Body_Image.pdf){target="_blank"} (2009)

**Questions to Consider**

After reading, consider the following questions and use them as a tool to help you process the information.

1. Why do research results suggest that bulimic symptoms are related to depression?
2. How much higher is the risk of suicide for those struggling with anorexia versus the broader public?
3. How are suicide ideation and body image related?
4. What did this study hypothesize or predict?
5. What was found to have a direct effect on suicide ideation?
6. What are the implications of these findings?
7. Was gender a factor in the results?
8. What are some of the limitations of this study?

:::

## Eating Disorders

The exact cause of eating disorders is unknown. As previously discussed, there are many possible causes of mental illness. Psychological, environmental, and social factors may contribute to the development of eating disorders in some individuals due to their genes and relational issues.

### Activity: Video | Eating Disorders and the Brain

::: {.learning-activity}

In this video you will learn how eating disorders affect the brain, and what is the difference between a well-functioning brain and a brain affected by an eating disorder.

- [*The Eating Disorder Brain vs. The Well Brain: Effects of the Starving Brain and Eating Disorders*](https://www.youtube.com/watch?v=V44xLqCmV2U){target="_blank"} (2021)

**Questions to Consider**

After watching the video, consider the following question and use it as a tool to help you process the information.

1. What is the difference between a well brain and an eating disorder brain?

:::

### Activity: Read | Eating Disorders and Generational influences

::: {.learning-activity}

As part of the EFFT curriculum we are taught that families have a profound impact on treatment outcomes. I have selected the following article in order to illustrate this point.

- [*Last Word: Ending the Intergenerational Transmission of Body Dissatisfaction and Disordered Eating: A Call to Investigate the Mother-Daughter Relationship*](https://doi-org.twu.idm.oclc.org/10.1080/10640266.2020.1712635){target="_blank"} (2021)

**Questions to Consider**

1. What is a predictor of subclinical and clinical eating disorders?
2. What do mothers act as and why is that important?
3. How can eating disorders be influenced directly and indirectly?
4. Did endorsing lower body satisfaction motivate girls to engage in healthful habits? Why or why not?
5. What is the "call to action?" What do the authors recommend?

:::

### Activity: Optional Read | Eating Disorders and Caregiver Involvement

::: {.learning-activity}

An important study related to eating disorders and EFFT intervention is reported in this research article. It is likely that by this point you will recognize some of the researchers’ names and have some understanding of some of the concepts they are discussing.

- [The Influence of Carer Fear and Self-Blame When Supporting a Loved One With an Eating Disorder](../U4%20Files/Article_EDEFFT.pdf){target="_blank"}, *Eating Disorders: The Journal of Treatment and Prevention* (2016).

**Questions to Consider**

After reading, consider the following questions and use them as a tool to help you process the information.

1. What was identified as the most necessary factor for a positive outcome for clients?
2. What was the result of the EFFT 2-day caregiver workshop?
3. What happens when caregivers experience intense emotion?
4. What is the hypothesis for this study? What are the authors hoping to prove?
5. What did they find that fear predicted?
6. What was one concern that was brought up about caregiver involvement? What were the suggestions to help mitigate this?

:::

# How Do We Work With Mental Health Issues

To effectively assist a client or friend or family member with a mental health issue it is helpful to know what resources are available both to support the client or loved one as well as to support you. As there are many variables to consider when treating mental health issues, each client’s treatment will differ. This topic will include readings and activities designed to facilitate this learning.

EFFT was developed as a result of studies conducted with people who suffer from eating disorders. Thus, you will find this section to be complementary to your learnings about EFFT. We will begin by exploring some of the community resources that are available.

### Activity: Explore | Community Resources

::: {.learning-activity}

Do you have access to any resources in the area where you work? When a crisis arises, how can you help? The following are just a few options available; we recommend exploring more.

**Suicidality**

- [*Lines for Life: Services and Crisis Lines*](https://www.linesforlife.org/services/?gclid=CjwKCAjwiJqWBhBdEiwAtESPaKW7--GMkzJZnQuCT_XwP3G6d21vLiBhQ9OKMoj7rF6IapSS2fHcsRoC2T8QAvD_BwE){target="_blank"} (n.d.)
- [*The Crisis Centre of BC*](https://crisiscentre.bc.ca/get-help/){target="_blank"} (n.d.)

**Depression**

- [*Healthline: How can I get Help for Depression*](https://www.healthline.com/health/depression/help-for-depression#other-treatments){target="_blank"} (2024)

**Eating Disorders**

- [*National Eating Disorder Information Centre*](https://nedic.ca/){target="_blank"} (n.d.)

**General Help**

- [*Foundry: You Matter*](https://foundrybc.ca/youmatter/?gclid=CjwKCAjwq5-WBhB7EiwAl-HEkk2herv2QF8l8z0Q5Afj8zb5XwY9G_3MzgcweKhJ5aUTuDU7vupErBoCNWcQAvD_BwE){target="_blank"} (n.d.)
- [*eMentalHealth*](https://www.ementalhealth.ca/){target="_blank"} (n.d.)

:::

### Activity: Practice | Emotion Coaching and Behaviour Coaching

::: {.learning-activity}

In this section we will practice our skills of emotion coaching and behaviour coaching. While this may seem repetitive, the more you practice, the easier it will become. The EFFT manual (Lafrance et al., 2020) contains suggestions for behaviour coaching strategies for depression, as well as what people with depression require in terms of emotional support. As an example, consider a scenario in which a parent seeks your assistance with their child who is suffering from depression. You will assist the parent in developing a script that they can use at home with their child.

Use the tool below to help in developing your script. Remember that if you close your browser, the work done will not be saved, so you might wish to download or save the file.

- <iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=483" width="100%" height="100%" frameborder="0" allowfullscreen="allowfullscreen" title=""></iframe><script src="https://h5p.org/sites/all/modules/h5p/library/js/h5p-resizer.js" charset="UTF-8"></script>

:::

### Activity: EFFT and Suicidality

::: {.learning-activity}

In order to conduct a preliminary assessment it is extremely important to understand the signs of possible suicidal behaviour. In accordance with the literature, the risk assessment should not be regarded as an absolute. Continual monitoring and assessment are essential, especially at the beginning of your career. One of the exceptions to confidentiality, (as has been discussed in SOCI 400) is when there is a risk of harm to oneself or another. Whenever you suspect that your client’s life is in danger, you must report it to the appropriate authorities.

- [*Suicide Risk: Detecting & Assessing Suicidality*](https://www.camh.ca/en/professionals/treating-conditions-and-disorders/suicide-risk/suicide---detecting-and-assessing-suicidality){target="_blank"} (2019)

For this section on suicide, you will write a validation statement that explains why someone might commit suicide. Suicide is one of the most difficult issues to validate, since when we validate it, especially in this circumstance, we might feel as though we are encouraging the individual to carry out the action. However, in keeping with what we have read and what the research shows, validation actually gives the other the feeling that they are not alone—that someone understands and is willing to share dark places with them.

This validation statement will not be accompanied by an actual scenario. Instead, imagine someone sitting in front of you saying, "I want to end my life," and think about why they might want to do so.

Use the tool below to assist you. Remember to save or download your work before you close your browser.

- <iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=484" width="100%" height="100%" frameborder="0" allowfullscreen="allowfullscreen" title=""></iframe><script src="https://h5p.org/sites/all/modules/h5p/library/js/h5p-resizer.js" charset="UTF-8"></script>

:::

### Activity: EFFT and Eating Disorders

::: {.learning-activity}

It has been shown in the literature that parental body image (in particular, a mother’s) and eating habits can be associated with the manifestation of an eating disorder in their loved one. Note that this is a correlation and not a causation. This is important in relieving caregiver self-blame, and then empowering a caregiver or parent to become a part of the healing process. There is evidence to support the benefits of caregiver involvement in the literature we have been reading.

If a caregiver has struggled or continues to struggle with an eating disorder or body dysmorphia, it may hinder their ability to participate in the healing process of their loved one.

Complete the exercise given in the tool below. Remember to save or download your work before you close your browser.

- <iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=485" width="100%" height="100%" frameborder="0" allowfullscreen="allowfullscreen" title=""></iframe><script src="https://h5p.org/sites/all/modules/h5p/library/js/h5p-resizer.js" charset="UTF-8"></script>

:::

# Unit 4 Resources

## What are Depression, Suicidality, and Eating Disorders?

**Videos**

- ABC News. (2016). *‘Suicide cluster’ in Palo Alto - Students share stories of anxiety, depression* [Video]. YouTube. [https://youtu.be/F6S3jcJ-Imw](https://youtu.be/F6S3jcJ-Imw){target="_blank"}

{{< video https://www.youtube-nocookie.com/embed/F6S3jcJ-Imw >}}

::: {.prote}

Bleep bloop: The above video was auto embedded. If it was just a link, I added a title. If you don't like the title, change it, and I'll leave it alone if I come across it again.

:::

- BreakfastAlien. (2014). *My suicide Shneidman sequence QT* [Video]. YouTube. [https://www.youtube.com/watch?v=0KAE5IGOTxw](https://www.youtube.com/watch?v=0KAE5IGOTxw){target="_blank"}

{{< video https://www.youtube-nocookie.com/embed/0KAE5IGOTxw >}}

::: {.prote}

Bleep bloop: The above video was auto embedded. If it was just a link, I added a title. If you don't like the title, change it, and I'll leave it alone if I come across it again.

:::

- Neuroscientifically Challenged (2023.). *10-minute neuroscience: Depression* [Video]. YouTube. [https://www.youtube-nocookie.com/embed/1euK8OSIR9E](https://www.youtube.com/watch?v=1euK8OSIR9E){target="_blank"}

{{< video https://www.youtube-nocookie.com/embed/1euK8OSIR9E >}}

::: {.prote}

Bleep bloop: The above video was auto embedded. If it was just a link, I added a title. If you don't like the title, change it, and I'll leave it alone if I come across it again.

:::

- TEDxTalks. (2020). *What I learned from my husband’s suicide - Lori Prichard* [Video]. YouTube. [https://youtu.be/Jb_1IklnhaU](https://youtu.be/Jb_1IklnhaU){target="_blank"}

{{< video https://www.youtube-nocookie.com/embed/Jb_1IklnhaU >}}

::: {.prote}

Bleep bloop: The above video was auto embedded. If it was just a link, I added a title. If you don't like the title, change it, and I'll leave it alone if I come across it again.

:::

- UNC-Chapel Hill. (2010). *Cynthia Bulik on eating disorders* [Video]. YouTube. [https://youtu.be/Fxe6WLNSxcw](https://youtu.be/Fxe6WLNSxcw){target="_blank"}

{{< video https://www.youtube-nocookie.com/embed/Fxe6WLNSxcw >}}

::: {.prote}

Bleep bloop: The above video was auto embedded. If it was just a link, I added a title. If you don't like the title, change it, and I'll leave it alone if I come across it again.

:::

- Yale Medicine (2021). *How depression affects the brain* [Video]. YouTube. [https://www.youtube.com/watch?v=BZOLxSQwER8](https://www.youtube.com/watch?v=BZOLxSQwER8){target="_blank"}

{{< video https://www.youtube-nocookie.com/embed/BZOLxSQwER8 >}}

::: {.prote}

Bleep bloop: The above video was auto embedded. If it was just a link, I added a title. If you don't like the title, change it, and I'll leave it alone if I come across it again.

:::

**Readings**

- Haw, C., Hawton, K., Niedzwiedz, C., & Platt, S. (2013). Suicide clusters: a review of risk factors and mechanisms. *Suicide & Life-Threatening Behavior, 43*(1), 97–108. [https://doi.org/10.1111/j.1943-278x.2012.00130.x](https://doi.org/10.1111/j.1943-278x.2012.00130.x){target="_blank"}
- Jobes, D. A., & Nelson, K. N. (2006). Schneidman’s contribution to the understanding of suicidal thinking. In T. E. Ellis (Ed.). Cognition and suicide: Theory, research, and therapy. American Psychological Association.
- Real, T. (1997). I don’t want to talk about it: Overcoming the secret legacy of male depression. Scribner.

**Websites**

- Government of British Columbia. (1999). Patient health questionnaire—PHQ-9. [https://www2.gov.bc.ca/assets/gov/health/practitioner-pro/bc-guidelines/depression_patient_health_questionnaire.pdf](https://www2.gov.bc.ca/assets/gov/health/practitioner-pro/bc-guidelines/depression_patient_health_questionnaire.pdf){target="_blank"}
- Treasure, J., Bektas, S., Mutwalli, G., Dhopatkar, N., & Himmerich, H. (2022). Novel approaches to tackling emotional loss of control of eating across the weight spectrum. *Nutrition Society Winter Meeting.* [https://www.cambridge.org](https://www.cambridge.org/core/journals/proceedings-of-the-nutrition-society/article/novel-approaches-to-tackling-emotional-loss-of-control-of-eating-across-the-weight-spectrum/320DBB5D71D83A6C8597BEFAE7BAAEA9){target="_blank"}

## What Causes Mental Health Issues?

**Videos**

- Amen Clinics (2019). The science behind suicidal thoughts with Dr. Daniel Amen [Video]. YouTube. [https://youtu.be/GJkTElq8UFM](https://youtu.be/GJkTElq8UFM){target="_blank"}

{{< video https://www.youtube-nocookie.com/embed/GJkTElq8UFM >}}

::: {.prote}

Bleep bloop: The above video was auto embedded. If it was just a link, I added a title. If you don't like the title, change it, and I'll leave it alone if I come across it again.

:::

- [The Eating Disorder Brain vs. The Well Brain | Effects of the Starving Brain and Eating Disorders](https://youtu.be/V44xLqCmV2U){target="_blank"}

{{< video https://www.youtube-nocookie.com/embed/V44xLqCmV2U >}}

::: {.prote}

Bleep bloop: The above video was auto embedded. If it was just a link, I added a title. If you don't like the title, change it, and I'll leave it alone if I come across it again.

:::

**Readings**

- Brausch, A. M., & Gutierrez, P. M. (2009). The role of body image and disordered eating as risk factors for depression and suicidal ideation in adolescents. *Suicide and Life-Threatening Behavior, 39*(1), 58–71. [https://doi.org/10.1521/suli.2009.39.1.58](https://doi.org/10.1521/suli.2009.39.1.58){target="_blank"}
- Brun, I., Russell-Mayhew, S., & Mudry, T. (2021). Last word: Ending the intergenerational transmission of body dissatisfaction and disordered eating: A call to investigate the mother-daughter relationship. *Eating Disorders, 29*(6), 591–598. [https://doi.org/10.1080/10640266.2020.1712635](https://doi.org/10.1080/10640266.2020.1712635){target="_blank"}
- Real, T. (1997). *I don’t want to talk about it: Overcoming the secret legacy of male depression.* Scribner.
- Stillar, A., Strahan, E., Nash, P., Files, N., Scarborough, J., Mayman, S., Henderson, K., Gusella, J., Connors, L., Orr, E. S., Marchand, P., Dolhanty, J. & Lafrance Robinson, A. (2016). The influence of carer fear and self-blame when supporting a loved one with an eating disorder. *Eating Disorders, 24*(2), 173–185. [https://doi.org/10.1080/10640266.2015.1133210](https://doi.org/10.1080/10640266.2015.1133210){target="_blank"}
- van Velzen, L. S., Toenders, Y. J., Kottaram, A., Youzchalveen, B., Pilkington, V., Cotton, S. M., Brooker, A., McKechnie, B., Rice, S., & Schmaal, L. (2022). Risk factors for suicide attempt during outpatient care in adolescents with severe and complex depression. *Crisis: The Journal of Crisis Intervention and Suicide Prevention, 44*(3), 232–239. [https://psycnet.apa.org/doi/10.1027/0227-5910/a000860](https://psycnet.apa.org/doi/10.1027/0227-5910/a000860){target="_blank"}

**Websites**

- There are no websites to review for this topic.

## How We Work with Mental Health Issues

**Videos**

- There are no videos to watch for this topic.

**Readings**

- There are no readings for this topic.

**Websites**

- eMental Health (n.d.). [https://www.ementalhealth.ca/](https://www.ementalhealth.ca/){target="_blank"}
- Foundry (n.d.). *You matter*. [https://foundrybc.ca/youmatter/?gclid=CjwKCAjwq5-WBhB7EiwAl-HEkk2herv2QF8l8z0Q5Afj8zb5XwY9G_3MzgcweKhJ5aUTuDU7vupErBoCNWcQAvD_BwE](https://foundrybc.ca/youmatter/?gclid=CjwKCAjwq5-WBhB7EiwAl-HEkk2herv2QF8l8z0Q5Afj8zb5XwY9G_3MzgcweKhJ5aUTuDU7vupErBoCNWcQAvD_BwE){target="_blank"}
- Healthline. (2024). *How can I get help for depression*. [https://www.healthline.com/health/depression/help-for-depression#other-treatments](https://www.healthline.com/health/depression/help-for-depression#other-treatments){target="_blank"}
- Lines for Life. (n.d.). *Services and crisis lines*. [https://www.linesforlife.org/get-help-now/services-and-crisis-lines/](https://www.linesforlife.org/get-help-now/services-and-crisis-lines/){target="_blank"}
- National Eating Disorder Information Centre. (n.d.). *Helpline*. [https://nedic.ca/](https://nedic.ca/){target="_blank"}
- The Crisis Centre of B. C. (n.d.). *Get support*. [https://www.crisiscentre.bc.ca/get-support/](https://www.crisiscentre.bc.ca/get-support/){target="_blank"}

## Summary {.unnumbered}

You have learned about three different major mental health issues in this fourth unit: depression, suicidality, and eating disorders. As part of this unit you have learned what a mental health issue is, why it occurs, and how it can be dealt with considering the resources available. Additionally, you have practiced with case scenarios. Having acquired a broad understanding of each mental health issue, you will be prepared to begin validating these very difficult conditions. In the event that you were triggered or stirred up in any way by this unit’s discussions, I encourage you to take care of yourself and seek out someone to talk to, as well as implement any other grounding techniques you find helpful.

::: {.check}

Before you move on to the next unit you may want to check that you are able to:

1. Demonstrate knowledge of some of the major researchers in the field of mental health
2. Engage in conversations about suicidality, eating disorders, and self-harm
3. Start conceptualizing mental health crisis cases
4. Practice the skill of validation as outlined in EFFT
5. Develop a preliminary treatment plan and know where to find resources and further specialized training

:::
